In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [12]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [8]:
#broadcasting in numpy
# price per unit is treated as np.array([1000, 400, 1200], [1000, 400, 1200], [1000, 400, 1200])
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [9]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [21]:
#exercise
ind_comp_revenue = np.array([[200,68,110,80],[220,79,140,85],[250,105,180,90]])
ind_comp_revenue*75

array([[15000,  5100,  8250,  6000],
       [16500,  5925, 10500,  6375],
       [18750,  7875, 13500,  6750]])

In [23]:
units = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30, 15])
units

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [24]:
np.dot(price_per_unit,units)

array([1900, 2640, 1430])