In [1]:
text = 'ice cream'
text[1]

'c'

In [2]:
#text[3] = 'F' # Strings are immutable

In [3]:
text[0:3] # first index is included and second index is excluded

'ice'

In [4]:
text[4:] # goes till end

'cream'

In [5]:
text[:5] # starts from beginning

'ice c'

In [6]:
address = '''29 haynes Avenue
St Catharines
Ontario, L2R 3Z5'''
print(address), address

29 haynes Avenue
St Catharines
Ontario, L2R 3Z5


(None, '29 haynes Avenue\nSt Catharines\nOntario, L2R 3Z5')

In [7]:
s ="Hello "
n = 0.07
s+str(n)

'Hello 0.07'

In [8]:
# Lists
items = ['b','p','v','f']
items[2]

'v'

In [9]:
items[-1], items[-2] # -1 means last element

('f', 'v')

In [10]:
items.append('c')
items

['b', 'p', 'v', 'f', 'c']

In [11]:
items.insert(1, 'd')
items

['b', 'd', 'p', 'v', 'f', 'c']

In [12]:
food =['a','b']
bathroom = ['c', 'd']
food+bathroom # caoncatenation

['a', 'b', 'c', 'd']

In [13]:
len(items)

6

In [14]:
'b' in items

True

In [15]:
for i in range(1,6):
    if(i%2==0):
        continue
    print(i*i)

1
9
25


In [16]:
#functions
""" Sum function which takes two arguments
And returns the final value
""" # documentation strings
def sum(a,b=1): # if b argument is not passed then its default value is given
    return a+b
sum(5)

6

In [17]:
sum(5,9)

14

In [18]:
# Dictionaries (Associate arrays, Hash Tables & Maps) and Tuples
d={
    "John" : "123456",
    "Rob": "435678",
    "Jill": "435453"
  }
d["John"]

'123456'

In [19]:
d["Sam"] = '783425'
d # Order doesn't matter

{'John': '123456', 'Rob': '435678', 'Jill': '435453', 'Sam': '783425'}

In [20]:
#Iterate each item
for key in d:
    print("key: ", key, "Value: ", d[key])

key:  John Value:  123456
key:  Rob Value:  435678
key:  Jill Value:  435453
key:  Sam Value:  783425


In [21]:
for k,v in d.items():
    print("key: ", k, "Value: ", v)

key:  John Value:  123456
key:  Rob Value:  435678
key:  Jill Value:  435453
key:  Sam Value:  783425


In [22]:
"John" in d

True

In [23]:
d.clear() # Wipe out all entries
d

{}

In [24]:
# Tuples - List of values are grouped together
point = (5,9)
point[0], point[1] # in tuple all the values has different meaning like X,Y - heterogeneous

(5, 9)

In [25]:
#point[0] = 6 # Tuples are immutable

In [26]:
# Modules
import math
math.sqrt(16), math.pow(2, 5), 2**5

(4.0, 32.0, 32)

In [27]:
# dir(math) gives me the information about math module

In [28]:
math.pi

3.141592653589793

In [29]:
import calendar
cal = calendar.month(2024,8)
print(cal)

    August 2024
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



In [30]:
calendar.isleap(2024)

True

In [31]:
import sys
#sys.path.append("Path of the code or py files")

In [32]:
book = {}
book['bob'] = {
    'name':'bob',
    'address':'1 brown street ON',
    'phone':'9090909090'
}
book['tom'] = {
    'name':'tom',
    'address':'1 green street ON',
    'phone':'8989898989'
}
import json
s = json.dumps(book) # dumping the dictionary object by converting into strings
s

'{"bob": {"name": "bob", "address": "1 brown street ON", "phone": "9090909090"}, "tom": {"name": "tom", "address": "1 green street ON", "phone": "8989898989"}}'

In [33]:
with open('C://Mappy//book.txt', 'w') as f:
    f.write(s)

In [34]:
json.loads(s) # this is a python dictionary that is coverted from a string

{'bob': {'name': 'bob', 'address': '1 brown street ON', 'phone': '9090909090'},
 'tom': {'name': 'tom', 'address': '1 green street ON', 'phone': '8989898989'}}

In [35]:
type(book), type(s)

(dict, str)

In [36]:
book['bob']['address']

'1 brown street ON'

In [37]:
f=open('C:\\Mappy\\book.txt', 'a') # w - overwrite the file a- append the content
f.write('\nPython is used in AM/AL')
f.close()

In [38]:
f=open('C:\\Mappy\\book.txt', 'r')
print(f.read())

{"bob": {"name": "bob", "address": "1 brown street ON", "phone": "9090909090"}, "tom": {"name": "tom", "address": "1 green street ON", "phone": "8989898989"}}
Python is used in AM/AL


In [39]:
f=open('C:\\Mappy\\book.txt', 'r') # r+ for both Write and read and w+ both for read write and create file
                                   #if doesn't exist and overwrite if exists
f_out=open('C:\\Mappy\\out.txt', 'w')
for line in f:
    tokens = line.split(' ')
    f_out.write(" wordcount : "+ str(len(tokens))+' '+ line)
    print(len(tokens))
f.close()
f_out.close()
#With statement we don't have to close the file explicitly and can be checked with f.closed flag 

20
5


In [40]:
#if __name__="__main__":   default value of __name__ is __main__ and acts as a entry point for a python program

In [41]:
# if executing same file then value remains __main__ and if we try 
# to import the file and call the imported function from the another file
# then the value of __main__ will be the module name from where that function is imported

In [42]:
x = input("Enter No : ")
y = input("Enter No : ")
try: 
    z = int(x)/int(y)
except Exception as e:
    print("Exception occured :", e)
    z=None
print("division is : ", z) # we can specition catch the exception like TypeError as e

Enter No : 1
Enter No : 1
division is :  1.0


In [43]:
#inheritance
class vehicle():
    def general_usage(self):
        print("General usage: Transportation")

class car(vehicle):
    def __init__(self):
        print("I am Car")
        self.wheels = 4
        self.has_roof = "Yes"
        
    def specific_usage(self):
        self.general_usage()
        print("Specific Usage: Vacation with Family")
    
class motorcycle(vehicle):
    def __init__(self):
        print("I am Motor Cycle")
        self.wheels = 2
        self.has_roof = "No"
    def specific_usage(self):
        self.general_usage()
        print("Specific Usage: Racing")
    
v = vehicle()
v.general_usage()
print(" ")
c = car()
#c.general_usage()
c.specific_usage()

print(" ")
m = motorcycle()
#m.general_usage()
m.specific_usage()

General usage: Transportation
 
I am Car
General usage: Transportation
Specific Usage: Vacation with Family
 
I am Motor Cycle
General usage: Transportation
Specific Usage: Racing


In [44]:
isinstance(c, car), isinstance(c, vehicle), isinstance(c, motorcycle)

(True, True, False)

In [45]:
# Multiple inheritance
class Father():
    def skills(self):
        print('gardening')
class Mother():
    def skills(self):
        print('cooking')
class Child(Father, Mother):
    def skills(self):
        Father.skills(self)
        Mother.skills(self)
        print("sports")
c = Child()
c.skills()

gardening
cooking
sports


In [46]:
# Exception part #2
try:
    raise MemoryError("memory error") # built in exception
except MemoryError as e:
    print(e)

memory error


In [47]:
class Accident(Exception):
    def __init__(self, msg):
        self.msg = msg
    def print_exception(self):
        print("User defined exception : ",self.msg)

try:
    raise Accident("Car crash")
except Accident as e:
    e.print_exception()

User defined exception :  Car crash


In [48]:
def process():
    try: 
        x =1/0
        y = 1+'a'
        ##f = open("data.txt")
    except ZeroDivisionError as e:
        print("Dividing a number by zero")
    finally:
        print("Catching all the other expections here")
process()
        

Dividing a number by zero
Catching all the other expections here


In [49]:
a = [1,2,3,4]
for i in a:
    print(i)
itr = iter(a)
next(itr)

1
2
3
4


1

In [50]:
next(itr)

2

In [51]:
next(itr)

3

In [52]:
itr = reversed(a)
next(itr)

4

In [53]:
next(itr)

3

In [54]:
next(itr)

2

In [55]:
# self iterator can be implemented by defining __iter__, __next__ and other relevant fucntions in the class

In [56]:
#Generators
def remote_control_next():
    yield 'Espn'
    yield 'Star Sprots 1'
    yield 'Star Sprots 2'

itr = remote_control_next()
itr

<generator object remote_control_next at 0x000001ABCEBF00B0>

In [57]:
next(itr)

'Espn'

In [58]:
next(itr)

'Star Sprots 1'

In [59]:
# loop works on genertors
for c in remote_control_next():
    print(c)

Espn
Star Sprots 1
Star Sprots 2


In [60]:
def fibonacci():
    a, b = 0,1
    while True:
        yield a
        a, b = b, a+b
        
for i in fibonacci():
    if(i > 50):
        break
    print(i)   

0
1
1
2
3
5
8
13
21
34


In [61]:
# comprehension
# list comprehension
numbers = [1,2,3,4,5,6,7]
even = []
for i in numbers:
    if i%2 == 0:
        even.append(i)
print(even)

[2, 4, 6]


In [62]:
even = [i for i in numbers if i%2 == 0]
even

[2, 4, 6]

In [63]:
squares = [i*i for i in numbers]
squares

[1, 4, 9, 16, 25, 36, 49]

In [64]:
# set - unordered collection of unique items
s = set([1,2,3,4,5,2,3])
s

{1, 2, 3, 4, 5}

In [65]:
even = {i for i in s if i%2 == 0}
even

{2, 4}

In [66]:
cities = ["Delhi", "Toronto", "Dubai"]
countries = ["India", "Canada", "UAE"]
z = zip(cities,countries)
z

In [67]:
for a in z:
    print(a)

('Delhi', 'India')
('Toronto', 'Canada')
('Dubai', 'UAE')


In [68]:
d ={city:country for city, country in zip(cities,countries)}
d

{'Delhi': 'India', 'Toronto': 'Canada', 'Dubai': 'UAE'}

In [69]:
# Sets and Frozen Sets
basket ={'Apple', "Banana", 'Apple'} #set
basket

{'Apple', 'Banana'}

In [70]:
type(basket)

set

In [71]:
a = set() # declaring by set class
a.add(1)
a.add(2)
type(a), a

(set, {1, 2})

In [72]:
x={} # By default it declares it a dict
type(x)

dict

In [73]:
numbers = [1,2,3,4,5,3,3,4,2,1,3,5,4,6,3,5,6,3,4,2,3,1]
unique_numbers = set(numbers)
unique_numbers.add(7)
unique_numbers

{1, 2, 3, 4, 5, 6, 7}

In [74]:
fs = frozenset(numbers)
fs

frozenset({1, 2, 3, 4, 5, 6})

In [75]:
# fs.add(7)  addition in frozen set is not allowed

In [76]:
x = {"a", "b", "c"}
y = {"1", "2", "c"}
x|y # union of sets

{'1', '2', 'a', 'b', 'c'}

In [77]:
x&y #intersection

{'c'}

In [78]:
x-y

{'a', 'b'}

In [79]:
x<y # is X is subset of Y

False

In [80]:
# Decorators
# functions in python are first class objects which means it can be passed as a argument to another function like a variable
# And it can be returned as return value from a function
import time

# creating a wrapper for the time calculation of a function
def time_it(func): 
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(func.__name__ + ' Took ' + str((end-start)*1000) +" ms")
        return result
    return wrapper
  
@time_it # decorated 
def calc_squares(numbers):
    #start = time.time()
    result = []
    for i in numbers:
        result.append(i*i)    
    #end = time.time()
    #print("Calc Square took :" + str((end-start)*1000) +" ms")
    return result

@time_it # decorated 
def calc_cubes(numbers):
    #start = time.time()
    result = []
    for i in numbers:
        result.append(i*i*i)
    #end = time.time()
    #print("Calc Cube took :" + str((end-start)*1000) +" ms")
    return result

array = range(0,100000)
squares = calc_squares(array)
cubes = calc_cubes(array)

calc_squares Took 10.259389877319336 ms
calc_cubes Took 13.113975524902344 ms


In [81]:
#Multithreading
import threading

def calc_squares(numbers):
    for i in numbers:
        time.sleep(0.2)
        print("Square :", (i*i))    
    #return result

def calc_cubes(numbers):
    for i in numbers:
        time.sleep(0.2)
        print("Cube :", (i*i*i))
    #return result
arr = [1,2,3,4,5]
t = time.time()
t1 = threading.Thread(target=calc_squares, args=(arr,))
t2 = threading.Thread(target=calc_cubes, args=(arr,))

t1.start()
t2.start()

t1.join() # Join function says that wait here untill the thread execution is done
t2.join()

#calc_squares(arr)
#calc_cubes(arr)

print("Done in :", str(time.time()-t) +" ms")

Square : 1
Cube : 1
Cube : 8
Square : 4
Cube :Square : 9
 27
Square : 16
Cube : 64
Cube :Square : 25
 125
Done in : 1.038557529449463 ms


In [98]:
#MultiProcessing
import time
import multiprocessing

def calc_squares(numbers):
    #time.sleep(5) # to see the processes in the Task Manager
    for i in numbers:
        print("Square :", (i*i))    

cube_result =[]        
def calc_cubes(numbers):
    global cube_result
    for i in numbers:
        cube_result.append(i*i*i)
        print("Cube :", (i*i*i))
        print('with in the process :', str(cube_result)) # here we get the values but somehow it is not printed

if __name__ == '__main__':
    arr = [1,2,3,4]
    p1 = multiprocessing.Process(target=calc_squares, args=(arr,))
    p2 = multiprocessing.Process(target=calc_cubes, args=(arr,))
    
    p1.start()
    p2.start()
    
    p1.join()
    p2.join()
    print('Result :', cube_result) # Cube result should have the results but it didn't 
                                   # because data is not shared among the different processes. Every Process has its own
                                   # address space, we need to create IPC for that to share it among the two processes. 
    ##print("Done !")
    

Result : []


In [106]:
# Sharing the data between Processes
import multiprocessing

def calc_squares(numbers, result, v): 
    v.value = 9.0
    for idx, n in enumerate(numbers):
        result[idx] = (n*n)
    
if __name__ == '__main__':
    arr = [3,5,7]
    result = multiprocessing.Array('i',3)
    v =multiprocessing.Value('d', 0.0)
    p1 = multiprocessing.Process(target=calc_squares, args=(arr,result, v))
    
    p1.start()
    p1.join()
    
    print(result[:])
    print(v.value)
# It works in VS code

[0, 0, 0]
0.0


In [107]:
# unit testing and process data sharing --skipped

In [111]:
#numpy arrays - less memory, fast, convinient

import numpy as np
import time
import sys

l=range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [119]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took "+ str((time.time()-start)*1000)+" ms")

start = time.time()
result = a1+a2 # this is not concetenation this is addition of 1st elem of both the arrays
print("Np array took "+ str((time.time()-start)*1000)+" ms")

Python list took 361.893892288208 ms
Np array took 24.024248123168945 ms


In [121]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [122]:
a.itemsize # byte size

4

In [123]:
a.dtype

dtype('int32')

In [126]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.float64) # dtype = complex is also possible
a.itemsize,a

(8,
 array([[1., 2.],
        [3., 4.],
        [5., 6.]]))

In [129]:
a.size # no of elements

6

In [130]:
a.shape # 3 rows 2 cols

(3, 2)

In [131]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [133]:
np.arange(1,5) # similar to range function

array([1, 2, 3, 4])

In [134]:
np.arange(1,5,2) # here 2 is step 

array([1, 3])

In [135]:
np.linspace(1,5,10) # create a 10 numbers from 1 to 5 and they are linearly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [137]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [139]:
a, a.shape

(array([[1., 2.],
        [3., 4.],
        [5., 6.]]),
 (3, 2))

In [144]:
a.reshape(2,3), a.reshape(6,1)

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]]))

In [146]:
a.ravel() # flatten your array # will not touch the original array and it returns array, you can save it in a variable

array([1., 2., 3., 4., 5., 6.])

In [147]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [148]:
a.min(), a.max(), a.sum()

(1.0, 6.0, 21.0)

In [149]:
# Axis 0 columns Axis 1 is rows
a.sum(axis=0)

array([ 9., 12.])

In [150]:
a.sum(axis=1)

array([ 3.,  7., 11.])

In [151]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [152]:
np.std(a)

1.707825127659933

In [155]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
np.dot(a,b)


# [1,2    * [5,6     [1*5+2*7=19,1*6+2*8=22  
#  3,4]      7,8] =   3*5+4*7=43, 3*6+4*8=50]

array([[19, 22],
       [43, 50]])

In [156]:
X = np.array([[7,8,9], [1,2,3], [4,5,6]])
X[1,2] # row 1 & col 2

3

In [157]:
X[0:2,2]

array([9, 3])

In [164]:
X[-1, :2]

array([4, 5])

In [165]:
 for row in X:
        print(row)

[7 8 9]
[1 2 3]
[4 5 6]


In [166]:
for cell in X.flat:
    print(cell)

7
8
9
1
2
3
4
5
6


In [172]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [175]:
np.vstack((a,b)), np.hstack((a,b))

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  1,  6,  7],
        [ 2,  3,  8,  9],
        [ 4,  5, 10, 11]]))

In [178]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [184]:
result = np.hsplit(a,3) # spliting the big array into 3 equal parts
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [185]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [187]:
b = np.vsplit(a,2)
b[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [189]:
c = np.arange(15).reshape(3,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [191]:
d = c >4
d

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [192]:
c[d] # returned an array where the element is true

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [194]:
c[d] = -2
c

array([[ 0,  1,  2,  3,  4],
       [-2, -2, -2, -2, -2],
       [-2, -2, -2, -2, -2]])

In [196]:
x = np.arange(15).reshape(3,5)
for cell in x.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [201]:
for cell in np.nditer(x, order='F', flags=['external_loop']): # C order and F is for Fotran order which is column wise
    # flags used for iteration method here external_loop means column by column
    print(cell)

[ 0  5 10]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]


In [205]:
# read write means we will iterate and simultaneously replace values in original array
for i in np.nditer(x, op_flags=['readwrite']): 
    i[...] = i*i
x

array([[    0,     1,    16,    81,   256],
       [  625,  1296,  2401,  4096,  6561],
       [10000, 14641, 20736, 28561, 38416]])

In [204]:
y = np.arange(3,15,4).reshape(3,1)
y

array([[ 3],
       [ 7],
       [11]])

In [206]:
# iterating both x, y arrays. Condition : x,y should be broadcastable 
for i,j in np.nditer([x,y]):
    print(i,j)

0 3
1 3
16 3
81 3
256 3
625 7
1296 7
2401 7
4096 7
6561 7
10000 11
14641 11
20736 11
28561 11
38416 11
